---
title: "ch 4 graphs"
author: "Simon C Stanton"
date: "2023-06-09"
output: html_document

params:
  exp_id: 398741
  sj_id: 0    # all
  game: "g111"  # All RGS
  tournament_set: "Final Round"
  model: "Single-Model"
  model_type: "_single" # 
  reward_upper_bound_game: 4000    #  game-theoretic
  mc_upper_bound_game: 1000         #  game-theoretic
  #reward_upper_bound_game: 64000    #  binary bandit
  #mc_upper_bound_game: 16000         #  binary bandit
  #reward_upper_bound_game: 52000    #  foundational RL, 1k
  #mc_upper_bound_game: 13000         #  foundational RL, 1k
  #reward_upper_bound_game: 520000    #  foundational RL, 10k
  #mc_upper_bound_game: 130000         #  foundational RL, 10k
  reward_upper_bound_rgs: 6336000   #  Tourney 4, 1k
  mc_upper_bound_rgs: 1584000        #  Tourney 4, 1k
  
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ggplot2)
library(dplyr)
library(ggrepel)
library(ggpubr)
library(stringr)


cbPalette <- c("#999999", "#E69F00", "#56B4E9", "#009E73", "#F0E442", "#0072B2", "#D55E00", "#CC79A7")
```

## R Markdown


```{r, import-data, echo=FALSE, include=FALSE}

path_to_data = "~/results/observations/tournament/"
view_path = "/view/ep_o/view_"
file_suffix_pre = "_sj_"
file_suffix_post = "_model_g111_trial_NBS.csv"  


filename = paste(path_to_data, params$exp_id, view_path, params$exp_id, file_suffix_pre, params$sj_id, file_suffix_post, sep="")
filename
df_data <- read.csv(file= filename, header=TRUE, check.names=FALSE)
#df_data$Agent <- as.factor(df_data$Agent)
summary(df_data)


```

## Alter data and plot

```{r plot, echo=FALSE}




df_data$A0_Reward_proportion =  df_data$R0 / params$reward_upper_bound_game
df_data$A1_Reward_proportion =  df_data$R1 / params$reward_upper_bound_game
df_data$MC_proportion = df_data$MC / params$mc_upper_bound_game

z0 <- df_data$A0
z1 <- df_data$A1
df_data$z2 <- paste(z0, "&",  z1) #str_pad(z, width = max(str_width(z)+2), side="both")
df_data$z2

df_data

```




```{r plot, echo=FALSE}
options(repr.plot.width = 8, repr.plot.height =6)

ggplot(df_data, aes(x=A0_Reward_proportion, y=A1_Reward_proportion, color=MC_proportion))  + 
  geom_point(color = "black", shape=1,  aes(size=MC_proportion)) +
  expand_limits(x=c(0,1), y=c(0,1)) +
  scale_y_continuous(breaks = seq(0, 1, by = .25)) +
  scale_x_continuous(breaks = seq(0, 1, by = .25)) +
  theme_bw() +
  theme(panel.grid.major = element_line(color = "lightgrey", linewidth = 0.2, linetype = 1),
        panel.grid.minor = element_line(color = "lightgrey", linewidth = 0.2, linetype = 3)) +
  labs(x="Agent Zero TR") +
  labs(y="Agent One TR") +
  theme(
    axis.title.x = element_text(margin = margin(t = 11), size=10, hjust=0.5),
    axis.title.y = element_text(margin = margin(r = 11), size=10),
  ) +
  geom_label_repel(aes(label = z2),
                   size = 2.5, # 3.5
                   label.padding = .28,
                   label.size = .2,
                   label.r = .25,
                   min.segment.length = unit(0, 'lines'),
                   segment.size=.18,
                   arrow = arrow(length = unit(0, "line"), type = "open"),
                   max.overlaps = Inf,
                   nudge_x=-0.099, 
                    nudge_y=0.014,
                   force=10

                   
  ) +
  labs(title = paste(params$model, "Tournament Summary"),
       subtitle = paste(params$tournament_set, "Match Pairings"),
       color="MC"
       ) +
  theme(plot.title = element_text(hjust = 0.5, size = 12),    # Center title position and size
    plot.subtitle = element_text(hjust = 0.5, size=10),            # Center subtitle
  ) +
  guides(color = FALSE) +
  guides(size=guide_legend(title="MC")) +
  theme(legend.title.align=0.5)  +
  annotate("text", x = 0.12, y = 0, label = paste("Model: ", params$game, " Exp_ID: ", params$exp_id, " 1k", sep=""), cex=3) 
#+
  #scale_fill_discrete(name = "New Legend Title") #

ggsave(path=".", filename=paste(params$exp_id, params$model_type, "-model", "_sj_", params$sj_id, "_", params$game, "_match-pairings.png", sep=""), bg='white', width=8, height=6 ) 


```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.



